spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:15532/postgres}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB

  domain-name: ${DOMAIN_NAME:russify.k-lab.su}

  jpa:
    hibernate:
      ddl-auto: none    # У нас схемой управлять будет liquibase так что вот так вот
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 30
        default_schema: app
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: public
    enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE

app:
  schemas: liquibase, app

s3:
  minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:miniopassword}
    buckets: ${MINIO_BUCKETS:music, images}

jwt:
  secret: my-super-secret-key-my-super-secret-key-my-super-secret-key
