spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none    # У нас схемой управлять будет liquibase так что вот так вот
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 30
        default_schema: app
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: public
    enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE

app:
  schemas: liquibase, app

s3:
  minio:
    url: http://minio:9000
    access-key: minioadmin
    secret-key: miniopassword
    buckets: music, images

jwt:
  secret: my-super-secret-key-my-super-secret-key-my-super-secret-key