services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d password" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "15532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "--console-address", ":9001", "/data" ]
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword

  minio-buckets:
    image: quay.io/minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set dockerminio http://minio:9000 minioadmin miniopassword;
      exit 0;
      "

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: RussifyService/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=miniopassword
      - DOMAIN_NAME=localhost
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"

volumes:
  postgres_data:
  minio-data:
